// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asgppqedrhwdsxpvoanu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZ3BwcWVkcmh3ZHN4cHZvYW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTAzODgsImV4cCI6MjA2MTM2NjM4OH0._FJhl5QvzYKE2eDFGXQGQCA4bLM8OVQuCLC0aR3Un1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);